[package]
name = "npuzzle_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
npuzzle_lib = { path = "../npuzzle_lib"}
clap = "2.33.3"
log = "0.4.14"
chrono = "0.4.19"